plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/sessions/magical-loving-albattani/mnt/Personal workout site "
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]